### ISSUE TITLE
constant crash

### ISSUE THREAD

**Issue by colin500** [manicdigger/manicdigger#191] opened 2015-03-28 01:24 UTC
when you play exstivly long after a while it crashes
and now in the new verion when i played once in single player it crashed and now will never let me play it. please fix and get the new version out by next monday if you can if not its ok.

thanks
colin500

**Comment by croxxx** [comment] 2015-03-28 11:40
A little more detail would be helpful.
- What Operating system do you use?
- Did you try creating a new singleplayer save?
- What exact error message do you get?

Crashing after playing for a long time is a bug we are working on.

**Comment by TBubba** [comment] 2015-04-07 22:15
Look after _ManicDiggerClientCrash.txt_ (it should be located in _...\ManicDigger\UserData\_) and post it here.

**Comment by colin500** [comment] 2015-04-09 03:44
windows xp with the crash
4/8/2015 9:37:54 PM: Critical error occurred
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ScreenMultiplayer.UpdateScrollButtons()
   at ScreenMultiplayer.Render(Single dt)
   at MainMenu.DrawScene(Single dt)
   at MainMenu.OnNewFrame(NewFrameEventArgs args)
   at MainMenuNewFrameHandler.OnNewFrame(NewFrameEventArgs args)
   at GamePlatformNative.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.OnRenderFrame(FrameEventArgs e)
   at OpenTK.GameWindow.OnRenderFrameInternal(FrameEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Stopwatch render_watch, Double& next_render, FrameEventArgs render_args)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run()
   at ManicDiggerProgram.Start(String[] args)
   at ManicDiggerProgram.<ManicDiggerProgram>c__AnonStorey0.<>m__0()
   at ManicDigger.ClientNative.CrashReporter.Start(ThreadStart start)

**Comment by TBubba** [comment] 2015-04-09 09:44
Cause:
The game crashes if you have certain resolutions in the server browser (since it tries to update server buttons with negative index due to a negative _serversPerPage_).

Solution:
Try playing with a taller window. The standard resolution should work fine.

(Sorry if my spelling is bad, I have no spellcheck on my phone)

**Comment by colin500** [comment] 2015-04-09 23:18
problem i cant play it and i do have it in a standard resolution

**Comment by croxxx** [comment] 2015-04-10 12:50
@colin500 To ensure that it wasn't a side effect, can you try downloading this version and see if it works?
http://files.croxxx.tk/ManicDiggerNightly2015-04-10.zip

Simply unzip the folder anywhere on you computer and run the contained *ManicDigger.exe*

**Comment by croxxx** [comment] 2015-07-17 17:53
Closing this as no further details have been provided and error could not be reproduced.

**Closed by croxxx** 2015-07-17 17:53 UTC
