### ISSUE TITLE
OnDialogClick not registering non letters

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#209] opened 2015-09-05 16:40 UTC
>I dont know if I did something wrong, but as far as I know, I have everything there to get the dialog click, but when I press - and = as to test it, it just doesn't want to work and its driving me crazy. I have `m.RegisterOnDialogClick(OnDialogClick);` and `void OnDialogClick(int player, string widgetid)` and 
`background.ClickKey = (char)'-';` but it just does not want to register it, `OnDialogClick()` seems to not even be called. I used `(char)45` also and ~~other inputs but still no success~~.

__UPDATE: 
Just tested using `(char)'z'` and `(char)'x'` and it works perfectly, how come - and = doesnt work?__

__Also when typing, the keys are logged also (`OnDialogClick()` still is called while typing in the text box.)__

__Keys that have been tested and does not work `- = [ ] \ ; ' , . /`__
__All letters seem to work and esc__

FULL CODE BELOW
```
FULL CODE REMOVED SINCE IT IS NOT THE FOCUS OF THE PROBLEM
```

**Comment by croxxx** [comment] 2015-09-08 22:00
I guess this is related to internal handling of character codes.
Will look into this the next days...

**Comment by croxxx** [comment] 2015-09-12 09:35
This behaviour is caused by a check for valid input characters.
You can see all allowed characters here: [Source](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Client/Mods/Dialog.ci.cs#L58)
```
"abcdefghijklmnopqrstuvwxyz1234567890\t "
```

I see this as intended and don't think it needs to be fixed.

**Comment by superstorm192** [comment] 2015-09-13 19:05
Intended or not, I feel that it would make things less "Why is it not working, everything is where it should be, im going crazy!"

I would really like to use the "-=[]\" characters on my soon-to-be released BlockCoord mod, but i am stuck using "zxcvg" and since the "new bar" is to the right of active materials, it would seem reasonable to use the "-=[]\" since it is directly to the right of "1234567890". And for dialogs it would make since to add all characters since ClickKey = (char)"-"

I think you should (when you have time) look a little deeper into that part of the code to see if there really is a reason someone only put letters and numbers and disinclude any symbols. (Actually, i could look through it a bit also)

**Comment by croxxx** [comment] 2015-09-13 19:58
Keep in mind that keyboard layouts vary per region.
So it might not be a good idea to use special characters...

**Comment by superstorm192** [comment] 2015-09-14 00:25
It might not be, but the main keys i want to use are right next to the number keys. i guess i can manage.

**Comment by croxxx** [comment] 2015-09-15 09:42
I guess this *could* be changed, but I still see special characters as a problem. At least as a source for confusion of users.
A "handy shortcut" for one might be a strange key combination for another user...

## ANSI Layout (US)
![](https://upload.wikimedia.org/wikipedia/commons/3/37/ANSI_Keyboard_Layout_Diagram_with_Form_Factor.svg)
## UK Layout
![](https://upload.wikimedia.org/wikipedia/commons/9/9c/ISO_keyboard_%28105%29_QWERTY_UK.svg)
## German layout
![](https://upload.wikimedia.org/wikipedia/commons/3/36/KB_Germany.svg)

**Comment by superstorm192** [comment] 2015-09-15 22:14
Hm... thank you for the handy keyboard visuals, i see what you are talking about. even the z in "zxcvg" format doesn't quite work out on german keyboard, hm... if there is a modding command to "getPlayersSelectedLanguage" be DE or EN, i can use that to tailor my mod to be functional with all. and `-=p[] `keys for English can be ```ß´pü+``` for German with an if statement in MY mod.

So allowing such characters (including german symbols) and a function to get the language setting would be the best way to tailor the experience of manic digger. Are there any other languages that i need to worry about right now?

**Comment by croxxx** [comment] 2015-09-25 17:58
I'm sorry but I see no need for special characters being recognized at the moment.
As there are more important things to take care of right now I'll close this.

**Closed by croxxx** 2015-09-25 17:58 UTC
Labels: client, enhancement, suggestion
