### ISSUE TITLE
Question (nofix): The m.RegisterOnBlockUpdate() Feedback Loop Phenomenon

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#216] opened 2015-10-02 03:34 UTC
suppose you have this simple code:
```
OnBlockUpdate(int x, int y, int z)
{
    if(m.GetBlock(x,y,z) == m.GetBlockId("Test"))
    {
        m.SetBlock(x+1,y+1,z+1,m.GetBlockId("Test"));
    }
}
```
The phenomenon occurs when the same block that is placed ahead (+i) is the same as the block checked for in the condition.

whenever `Test` is found, you would expect it to just place one block, but by the nature of `m.RegisterOnBlockUpdate();` it turns out to be an infinite feedback loop. I know that a fix to this issue is impossible, but is there a workaround to this infinite feedback loop?

And yes, I am trying to do a similar (and confined) thing in game for a practical application of expanding growth of a plant, but i really didn't want an infinite expansion, i might find out a workaround but what are your thoughts about this runaway feedback loop?

**Comment by croxxx** [comment] 2015-10-02 11:09
What you describe as *infinite loop* is actually intended behaviour, if I understand your intention correctly.

Any function registered using `RegisterOnBlockUpdate()` will be called for **every block on the map** every 5 or 10 minutes (not sure about interval currently).
This handling of block goes from 0,0,0 to maximum map size for every dimension.
Therefore if you place a new block ahead of the current position in that check-loop it will be called again on the newly placed block when the loop reaches it.

**Comment by superstorm192** [comment] 2015-10-02 21:02
Exactly, I am thinking that i could have a dictionary and check to see what block is at x+1,y+1,z+1 and check THAT instead of the actual block there (simulating a world that the actions occur AFTER the entire map has been scanned, thus overcoming the infinite loop. I think that could be a good workaround, if you have any better ideas, im all ears.

**Comment by croxxx** [comment] 2015-10-04 17:03
I will close this as the behaviour is no game defect.
For general development questions please use the forum.

**Closed by croxxx** 2015-10-04 17:03 UTC
Labels: question, server, wontfix
