### ISSUE TITLE
Sunlevel problem

### ISSUE THREAD

**Issue by kennyvv** [manicdigger/manicdigger#157] opened 2015-01-09 22:57 UTC
Whenever i connect, i will get this error in the console:

System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Server.SendSunLevels(Int32 clientid)
   at Server.TryReadPacket(Int32 clientid, Byte[] data)
   at Server.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket, Sto
pwatch s)

(And offcourse i instantly get disconnected because of that)

**Comment by croxxx** [comment] 2015-01-09 23:12
Does this only happen when you create an own server or also when connecting to online servers?

If you're running Mono it might be a problem caused by a Mod not compiling correctly.
To see if everything is loaded correctly, you can run the standalone server. It shows errors occuring during startup in console.

**Comment by kennyvv** [comment] 2015-01-09 23:19
Some more information:
Server compiled with xBuild with arguments: /p:Configuration=Release
to make sure it was build as release version.

After that build.bat is ran.
Ran the exe in the output folder to start the server.

Running on Windows server 2008 R2 Enterprise.

**Comment by TobiMob** [comment] 2015-01-14 21:43
I get the same error, if i rename my mods folder.
So it seems like the mod could not be found / loaded.

Could you debug in the ModLoader and see if the mod folder can be found.
_ManicDiggerLib/Server/Systems/ModLoader.cs Line 93_
```cs
93            foreach (string modpath in modpaths)
94            {
95                if (!Directory.Exists(modpath))
96                {
97                    continue;
98                }
99                server.ModPaths.Add(modpath);
```

**Comment by croxxx** [comment] 2015-04-10 12:54
Is this still an issue?
I could not reproduce the error with default game configuration.

**Comment by croxxx** [comment] 2015-07-17 19:22
Closing this as not reproducable on default setup.

**Closed by croxxx** 2015-07-17 19:22 UTC
