### ISSUE TITLE
Error flooding when at positive corner of map

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#237] opened 2015-12-30 07:39 UTC
Going to the zero corner of the map is just fine, but when you go to the other corner (the extreme positive), your server console gets flooded with these error messages.

![image](https://cloud.githubusercontent.com/assets/10588108/12047718/d109ed5c-ae95-11e5-9ab2-ee2eaf88e48c.png)

if the character is quick to respawn/logout the messages stop, but if they are not quick enough, the whole server grinds to a halt trying to spit out all of those error messages.

**Comment by croxxx** [comment] 2015-12-30 12:38
As you can clearly see in the error message this is caused by a particular Mod you have installed (`NewBlockIds`) trying to access blocks that don't exist.
You might want to have a look at `m.IsValidPos(x, y, z);`
https://github.com/manicdigger/manicdigger/blob/master/ScriptingApi/ModManager.cs#L135

Closing this issue as it is not related to core mods.

**Comment by superstorm192** [comment] 2015-12-30 16:00
I do not have anything in this mod that would cause this, for this particular mod is very tiny. The only thing involving blocks is a simple block of code, which should NOT produce the error in the first place. The `m.RegisterOnBlockUpdate()` itself is not pre protected. I believe it should be, after all it should only check blocks INSIDE of the array anyways. (Why does it not error out at zero?)
```
        void Update(int x, int y, int z){
            int block = m.GetBlock(x,y,z);
            if(block == ULight_off)
            {
                m.SetBlock(x,y,z,ULight_on);
            }
            else if(block == ULight_on)
            {
                m.SetBlock(x,y,z,ULight_off);
            }
        }
```

**Comment by superstorm192** [comment] 2015-12-30 16:16
Also, after looking at the different mods that produced this error, I came across a core mod :D
![image](https://cloud.githubusercontent.com/assets/10588108/12053401/5b78e356-aede-11e5-92a4-e57e6648fd2e.png)

**Comment by croxxx** [comment] 2015-12-30 20:59
This is definitely not supposed to happen.
I could not find the cause when doing a quick search, though. If you find out more details, please let me know.

**Comment by superstorm192** [comment] 2015-12-31 06:46
Here is one area i think the problem could be...
```
root/ManicDiggerLib/Server/ServerMap.cs
public override int GetBlock(int x, int y, int z)
{
    ServerChunk chunk = GetChunk(x, y, z);
    //return chunk.data[MapUtilCi.Index3d(x % chunksize, y % chunksize, z % chunksize, chunksize, chunksize)];
    unchecked
    {
        return chunk.data[MapUtilCi.Index3d(moduloChunk(x), moduloChunk(y), moduloChunk(z), chunksize, chunksize)];
    }
}
```
It does say unchecked, not sure why. If there really is no problem i think one solution could be this below. But if it is supposed to be unchecked for some reason then find the OnBlockUpdate command and send it there.
```
root/ManicDiggerLib/Server/ServerMap.cs
public override int GetBlock(int x, int y, int z)
{
    ServerChunk chunk = GetChunk(x, y, z);
    //return chunk.data[MapUtilCi.Index3d(x % chunksize, y % chunksize, z % chunksize, chunksize, chunksize)];
    if(MapUtil.IsValidPos(server.d_Map, x, y, z))
    {
        return chunk.data[MapUtilCi.Index3d(moduloChunk(x), moduloChunk(y), moduloChunk(z), chunksize, chunksize)];
    }
}
```

**Comment by croxxx** [comment] 2015-12-31 14:21
I found the issue being caused by commit a5ed76b1ee24e0d07664c0b9f78df1a6da5345b9.
Most likely this part: https://github.com/manicdigger/manicdigger/commit/a5ed76b1ee24e0d07664c0b9f78df1a6da5345b9#diff-1c6553a592eed306a393bc9fd90ca277R122

By commenting these out the implicit rounding happening before (not the best way to do this, TBH) did not take place anymore, resulting in player positions not being multiples of server chunk size.

Example for x=9980, chunksize=32:
```csharp
playerpos.x =  (playerpos.x / Server.chunksize) * Server.chunksize;
playerpos.x =  (9980 / 32) * 32;
playerpos.x =  ((int)311,875) * 32;
playerpos.x =  311 * 32;
playerpos.x =  9952;
```
As can be seen above skipping this correction to multiples of server chunk size will lead to the for-loop iterating over all loaded chunks near a player on block updates to run out of bounds.

***

As the commit itself is doubted to be useful anyway it has been rolled back. So has been a change to adress that very same problem you experienced: e99d23236e98f8e851672e704b4ace0765a30385

After applying those changes the faulty behaviour seems to be fixed. Please verify this by running the latest build provided here in a few minutes: https://github.com/manicdigger/manicdigger-builds
Should the issue persist, please reopen this.

**Closed by croxxx** 2015-12-31 14:21 UTC
Labels: bug, server

**Comment by superstorm192** [comment] 2015-12-31 17:14
``VegetationGrowth.cs`` has not been updated, but from the looks of this, I am not getting those errors anymore so it is fine as it is, no update needed. Thanks for implementing a fix for the next public release.
