### ISSUE TITLE
Crash when opening inventory

### ISSUE THREAD

**Issue by Wayward1** [manicdigger/manicdigger#247] opened 2016-05-24 20:22 UTC
Using a Windows 10 tablet PC with the virtual keyboard and a USB mouse, opening the inventory in singleplayer results in this crash: http://paste.ubuntu.com/16664999/

**Comment by croxxx** [comment] 2017-03-04 13:11
Thanks for your feedback!
I have done some testing and unfortunately was not able to reproduce the issue.

Could you test this using one of the latest builds [from here](https://github.com/manicdigger/manicdigger-builds) and see if the issue persists?
If it does, can you please detail the process to cause the error?

**Comment by Wayward1** [comment] 2017-03-04 22:22
Unfortunately, the device used originally is too unstable now to provide reliable information, so I can't perform a 100% accurate retest under the same conditions. However, I was able to retest it on a Windows 10 touchscreen laptop using the virtual keyboard and USB mouse and have not encountered this issue any more. 

Further information:
The original device was a Vulcan Voyager 7" tablet PC with Windows 10 x86 using an Intel Atom Z3735G CPU with Intel HD Graphics.
The current device is an HP Pavilion 15-p030nr touchscreen laptop with Windows 10 x64 using an AMD A series A8-5545M APU with AMD Radeon HD 8510G graphics.

**Comment by Wayward1** [comment] 2017-03-05 02:56
Unfortunately, the device used originally is too unstable now to provide reliable information, so I can't perform a 100% accurate retest. However, I was able to test it on a Windows 10 touchscreen laptop using the virtual keyboard and the USB mouse and have not encountered this issue any more.

**Comment by Wayward1** [comment] 2017-03-05 02:57
Oops, wrong button

**Comment by croxxx** [comment] 2017-04-08 19:33
Closing this issue as I was not able to reproduce this and there is not enough information to determine the exact cause.

**Closed by croxxx** 2017-04-08 19:33 UTC
